name: yandex_todo
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.1 <4.0.0"

dependencies:
  bloc_concurrency: ^0.2.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  intl: ^0.18.1
  logging: ^1.2.0
  rxdart: ^0.27.7
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  merch_lints: any

flutter:
  uses-material-design: true
